/***************************************************************************
 *             __________               __   ___.
 *   Open      \______   \ ____   ____ |  | _\_ |__   _______  ___
 *   Source     |       _//  _ \_/ ___\|  |/ /| __ \ /  _ \  \/  /
 *   Jukebox    |    |   (  <_> )  \___|    < | \_\ (  <_> > <  <
 *   Firmware   |____|_  /\____/ \___  >__|_ \|___  /\____/__/\_ \
 *                     \/            \/     \/    \/            \/
 * $Id$
 *
 * Copyright (C) 2014 Arnd Oberländer
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ****************************************************************************/

#include "plugin.h"

#include "lib/highscore.h"

#include "pluginbitmaps/threes_border.h"
#include "pluginbitmaps/threes_border_blue.h"
#include "pluginbitmaps/threes_border_red.h"
#include "pluginbitmaps/threes_numbers_opensans.h"

#define ROW_COUNT 4
#define COL_COUNT 4
#define TOOLBAR_HEIGHT 11
#define MARGIN 1
#define CELL_SPACING 2
#define CARD_WIDTH  (LCD_WIDTH - 2*MARGIN - 3*CELL_SPACING)/ROW_COUNT
#define CARD_HEIGHT (LCD_HEIGHT - TOOLBAR_HEIGHT - 2*MARGIN - 3*CELL_SPACING)/COL_COUNT
#define START_COUNT 9
#define SCORE_FILE  PLUGIN_GAMES_DATA_DIR "/threes.score"
#define NUM_SCORES  5

/*
 * Direction
 *          3 - UP
 *  0 - LEFT        1 - RIGHT
 *          2 - DOWN
 */
#define LEFT 0
#define RIGHT 1
#define UP 2
#define DOWN 3


/* variable button definitions */
#if CONFIG_KEYPAD == RECORDER_PAD
#define THREES_BUTTON_QUIT BUTTON_OFF
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_PLAY
#define THREES_BUTTON_MENU BUTTON_F1
#define THREES_BUTTON_POSSIBLE BUTTON_F2

#elif CONFIG_KEYPAD == ARCHOS_AV300_PAD
#define THREES_BUTTON_QUIT BUTTON_OFF
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_SELECT
#define THREES_BUTTON_MENU BUTTON_F1
#define THREES_BUTTON_POSSIBLE BUTTON_F2

#elif CONFIG_KEYPAD == ONDIO_PAD
#define THREES_BUTTON_QUIT BUTTON_OFF
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_ALTTOGGLE (BUTTON_MENU | BUTTON_DOWN)
#define THREES_BUTTON_TOGGLE_PRE BUTTON_MENU
#define THREES_BUTTON_TOGGLE (BUTTON_MENU | BUTTON_REL)
#define THREES_BUTTON_MENU_PRE BUTTON_MENU
#define THREES_BUTTON_MENU (BUTTON_MENU | BUTTON_REPEAT)
#define THREES_BUTTON_POSSIBLE (BUTTON_MENU | BUTTON_LEFT)

#elif (CONFIG_KEYPAD == IRIVER_H100_PAD) || \
      (CONFIG_KEYPAD == IRIVER_H300_PAD)
#define THREES_BUTTON_QUIT BUTTON_OFF
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_ALTTOGGLE BUTTON_ON
#define THREES_BUTTON_TOGGLE BUTTON_SELECT
#define THREES_BUTTON_MENU BUTTON_MODE
#define THREES_BUTTON_POSSIBLE BUTTON_REC

#elif (CONFIG_KEYPAD == IPOD_4G_PAD) || \
      (CONFIG_KEYPAD == IPOD_3G_PAD) || \
      (CONFIG_KEYPAD == IPOD_1G2G_PAD)
#define THREES_BUTTON_MENU       BUTTON_MENU
#define THREES_BUTTON_LEFT       BUTTON_SCROLL_BACK
#define THREES_BUTTON_RIGHT      BUTTON_SCROLL_FWD
#define THREES_BUTTON_CHANGEDIR  BUTTON_SELECT
#define THREES_BUTTON_TOGGLE     BUTTON_RIGHT
#define THREES_BUTTON_TOGGLEBACK BUTTON_LEFT
#define THREES_BUTTON_POSSIBLE   BUTTON_PLAY

#elif (CONFIG_KEYPAD == IAUDIO_X5M5_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_SELECT
#define THREES_BUTTON_MENU BUTTON_PLAY
#define THREES_BUTTON_POSSIBLE BUTTON_REC

#elif (CONFIG_KEYPAD == GIGABEAT_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_SELECT
#define THREES_BUTTON_MENU BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_A

#elif (CONFIG_KEYPAD == GIGABEAT_S_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_SELECT
#define THREES_BUTTON_MENU BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_PLAY

#elif (CONFIG_KEYPAD == IRIVER_H10_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_SCROLL_UP
#define THREES_BUTTON_DOWN BUTTON_SCROLL_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_REW
#define THREES_BUTTON_MENU BUTTON_PLAY
#define THREES_BUTTON_POSSIBLE BUTTON_FF

#elif (CONFIG_KEYPAD == SANSA_E200_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLEBACK BUTTON_SCROLL_BACK
#define THREES_BUTTON_TOGGLE BUTTON_SCROLL_FWD
#define THREES_BUTTON_MENU BUTTON_SELECT
#define THREES_BUTTON_POSSIBLE BUTTON_REC

#elif (CONFIG_KEYPAD == SANSA_FUZE_PAD)
#define THREES_BUTTON_QUIT      (BUTTON_HOME|BUTTON_REPEAT)
#define THREES_BUTTON_UP        BUTTON_UP
#define THREES_BUTTON_DOWN      BUTTON_DOWN
#define THREES_BUTTON_LEFT      BUTTON_LEFT
#define THREES_BUTTON_RIGHT     BUTTON_RIGHT
#define THREES_BUTTON_TOGGLEBACK BUTTON_SCROLL_BACK
#define THREES_BUTTON_TOGGLE    BUTTON_SCROLL_FWD
#define THREES_BUTTON_MENU      (BUTTON_HOME | BUTTON_REL)
#define THREES_BUTTON_POSSIBLE  BUTTON_SELECT

#elif (CONFIG_KEYPAD == SANSA_C200_PAD)
#define THREES_BUTTON_QUIT_PRE   BUTTON_POWER
#define THREES_BUTTON_QUIT       (BUTTON_POWER | BUTTON_REPEAT)
#define THREES_BUTTON_UP         BUTTON_UP
#define THREES_BUTTON_DOWN       BUTTON_DOWN
#define THREES_BUTTON_LEFT       BUTTON_LEFT
#define THREES_BUTTON_RIGHT      BUTTON_RIGHT
#define THREES_BUTTON_TOGGLEBACK BUTTON_VOL_DOWN
#define THREES_BUTTON_TOGGLE     BUTTON_VOL_UP
#define THREES_BUTTON_ALTTOGGLE  BUTTON_SELECT
#define THREES_BUTTON_MENU_PRE   BUTTON_POWER
#define THREES_BUTTON_MENU       (BUTTON_POWER | BUTTON_REL)
#define THREES_BUTTON_POSSIBLE   BUTTON_REC

#elif (CONFIG_KEYPAD == SANSA_CLIP_PAD)
#define THREES_BUTTON_QUIT_PRE   BUTTON_POWER
#define THREES_BUTTON_QUIT       (BUTTON_POWER | BUTTON_REPEAT)
#define THREES_BUTTON_UP         BUTTON_UP
#define THREES_BUTTON_DOWN       BUTTON_DOWN
#define THREES_BUTTON_LEFT       BUTTON_LEFT
#define THREES_BUTTON_RIGHT      BUTTON_RIGHT
#define THREES_BUTTON_TOGGLEBACK BUTTON_VOL_DOWN
#define THREES_BUTTON_TOGGLE     BUTTON_VOL_UP
#define THREES_BUTTON_ALTTOGGLE  BUTTON_SELECT
#define THREES_BUTTON_MENU_PRE   BUTTON_POWER
#define THREES_BUTTON_MENU       (BUTTON_POWER | BUTTON_REL)
#define THREES_BUTTON_POSSIBLE   BUTTON_HOME

#elif (CONFIG_KEYPAD == SANSA_M200_PAD)
#define THREES_BUTTON_QUIT_PRE   BUTTON_POWER
#define THREES_BUTTON_QUIT       (BUTTON_POWER | BUTTON_REPEAT)
#define THREES_BUTTON_UP         BUTTON_UP
#define THREES_BUTTON_DOWN       BUTTON_DOWN
#define THREES_BUTTON_LEFT       BUTTON_LEFT
#define THREES_BUTTON_RIGHT      BUTTON_RIGHT
#define THREES_BUTTON_TOGGLEBACK BUTTON_VOL_DOWN
#define THREES_BUTTON_TOGGLE     BUTTON_VOL_UP
#define THREES_BUTTON_ALTTOGGLE  (BUTTON_SELECT | BUTTON_REL)
#define THREES_BUTTON_MENU_PRE   BUTTON_POWER
#define THREES_BUTTON_MENU       (BUTTON_POWER | BUTTON_REL)
#define THREES_BUTTON_POSSIBLE   (BUTTON_SELECT | BUTTON_UP)

#elif CONFIG_KEYPAD == MROBE500_PAD
#define THREES_BUTTON_QUIT       BUTTON_POWER

#elif (CONFIG_KEYPAD == MROBE100_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_SELECT
#define THREES_BUTTON_MENU BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_DISPLAY

#elif CONFIG_KEYPAD == IAUDIO_M3_PAD
#define THREES_BUTTON_QUIT BUTTON_RC_REC
#define THREES_BUTTON_UP BUTTON_RC_VOL_UP
#define THREES_BUTTON_DOWN BUTTON_RC_VOL_DOWN
#define THREES_BUTTON_LEFT BUTTON_RC_REW
#define THREES_BUTTON_RIGHT BUTTON_RC_FF
#define THREES_BUTTON_TOGGLE BUTTON_RC_MODE
#define THREES_BUTTON_MENU BUTTON_RC_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_RC_PLAY

#elif (CONFIG_KEYPAD == COWON_D2_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_MENU BUTTON_MENU

#elif CONFIG_KEYPAD == IAUDIO67_PAD
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_STOP
#define THREES_BUTTON_DOWN BUTTON_PLAY
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_VOLUP
#define THREES_BUTTON_MENU BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_VOLDOWN

#elif CONFIG_KEYPAD == CREATIVEZVM_PAD
#define THREES_BUTTON_QUIT BUTTON_BACK
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_SELECT
#define THREES_BUTTON_MENU BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_PLAY

#elif CONFIG_KEYPAD == PHILIPS_HDD1630_PAD
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_SELECT
#define THREES_BUTTON_MENU BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_VIEW

#elif CONFIG_KEYPAD == PHILIPS_HDD6330_PAD
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE BUTTON_PLAY
#define THREES_BUTTON_MENU BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_NEXT

#elif CONFIG_KEYPAD == PHILIPS_SA9200_PAD
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_PREV
#define THREES_BUTTON_RIGHT BUTTON_NEXT
#define THREES_BUTTON_TOGGLE BUTTON_PLAY
#define THREES_BUTTON_MENU BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_RIGHT

#elif (CONFIG_KEYPAD == ONDAVX747_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_MENU BUTTON_MENU

#elif (CONFIG_KEYPAD == ONDAVX777_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER

#elif CONFIG_KEYPAD == SAMSUNG_YH_PAD
#define THREES_BUTTON_QUIT     BUTTON_REC
#define THREES_BUTTON_UP       BUTTON_UP
#define THREES_BUTTON_DOWN     BUTTON_DOWN
#define THREES_BUTTON_LEFT     BUTTON_LEFT
#define THREES_BUTTON_RIGHT    BUTTON_RIGHT
#define THREES_BUTTON_TOGGLE   BUTTON_FFWD
#define THREES_BUTTON_MENU     BUTTON_PLAY
#define THREES_BUTTON_POSSIBLE BUTTON_REW

#elif CONFIG_KEYPAD == PBELL_VIBE500_PAD
#define THREES_BUTTON_QUIT     BUTTON_REC
#define THREES_BUTTON_UP       BUTTON_UP
#define THREES_BUTTON_DOWN     BUTTON_DOWN
#define THREES_BUTTON_LEFT     BUTTON_PREV
#define THREES_BUTTON_RIGHT    BUTTON_NEXT
#define THREES_BUTTON_TOGGLE   BUTTON_OK
#define THREES_BUTTON_MENU     BUTTON_MENU
#define THREES_BUTTON_POSSIBLE BUTTON_PLAY

#elif CONFIG_KEYPAD == MPIO_HD200_PAD
#define THREES_BUTTON_QUIT       (BUTTON_REC | BUTTON_PLAY)
#define THREES_BUTTON_MENU       BUTTON_REC
#define THREES_BUTTON_UP         BUTTON_FF
#define THREES_BUTTON_DOWN       BUTTON_REW
#define THREES_BUTTON_LEFT       BUTTON_VOL_DOWN
#define THREES_BUTTON_RIGHT      BUTTON_VOL_UP
#define THREES_BUTTON_TOGGLE     BUTTON_FUNC
#define THREES_BUTTON_POSSIBLE   BUTTON_PLAY

#elif CONFIG_KEYPAD == MPIO_HD300_PAD
#define THREES_BUTTON_QUIT       (BUTTON_MENU | BUTTON_REPEAT)
#define THREES_BUTTON_MENU       (BUTTON_MENU | BUTTON_REL)
#define THREES_BUTTON_UP         BUTTON_UP
#define THREES_BUTTON_DOWN       BUTTON_DOWN
#define THREES_BUTTON_LEFT       BUTTON_REW
#define THREES_BUTTON_RIGHT      BUTTON_FF
#define THREES_BUTTON_TOGGLE     BUTTON_ENTER
#define THREES_BUTTON_POSSIBLE   BUTTON_PLAY

#elif CONFIG_KEYPAD == SANSA_FUZEPLUS_PAD
#define THREES_BUTTON_QUIT       BUTTON_POWER
#define THREES_BUTTON_MENU       BUTTON_BACK
#define THREES_BUTTON_LEFT       BUTTON_LEFT
#define THREES_BUTTON_RIGHT      BUTTON_RIGHT
#define THREES_BUTTON_UP         BUTTON_UP
#define THREES_BUTTON_DOWN       BUTTON_DOWN
#define THREES_BUTTON_TOGGLE     BUTTON_SELECT
#define THREES_BUTTON_TOGGLEBACK BUTTON_BOTTOMLEFT
#define THREES_BUTTON_POSSIBLE   BUTTON_PLAYPAUSE
#define THREES_BUTTON_ALTTOGGLE  BUTTON_BOTTOMRIGHT

#elif (CONFIG_KEYPAD == SANSA_CONNECT_PAD)
#define THREES_BUTTON_QUIT BUTTON_POWER
#define THREES_BUTTON_UP BUTTON_UP
#define THREES_BUTTON_DOWN BUTTON_DOWN
#define THREES_BUTTON_LEFT BUTTON_LEFT
#define THREES_BUTTON_RIGHT BUTTON_RIGHT
#define THREES_BUTTON_TOGGLEBACK BUTTON_PREV
#define THREES_BUTTON_TOGGLE BUTTON_NEXT
#define THREES_BUTTON_MENU BUTTON_SELECT
#define THREES_BUTTON_POSSIBLE BUTTON_VOL_DOWN

#elif CONFIG_KEYPAD == SAMSUNG_YPR0_PAD
#define THREES_BUTTON_QUIT       BUTTON_BACK
#define THREES_BUTTON_UP         BUTTON_UP
#define THREES_BUTTON_DOWN       BUTTON_DOWN
#define THREES_BUTTON_LEFT       BUTTON_LEFT
#define THREES_BUTTON_RIGHT      BUTTON_RIGHT
#define THREES_BUTTON_MENU       BUTTON_MENU
#define THREES_BUTTON_TOGGLE     BUTTON_SELECT
#define THREES_BUTTON_POSSIBLE   BUTTON_USER

#elif CONFIG_KEYPAD == HM60X_PAD
#define THREES_BUTTON_QUIT       BUTTON_POWER
#define THREES_BUTTON_MENU       (BUTTON_POWER | BUTTON_LEFT)
#define THREES_BUTTON_LEFT       BUTTON_LEFT
#define THREES_BUTTON_RIGHT      BUTTON_RIGHT
#define THREES_BUTTON_UP         BUTTON_UP
#define THREES_BUTTON_DOWN       BUTTON_DOWN
#define THREES_BUTTON_TOGGLE     BUTTON_SELECT
#define THREES_BUTTON_TOGGLEBACK (BUTTON_POWER | BUTTON_RIGHT)
#define THREES_BUTTON_POSSIBLE   (BUTTON_POWER | BUTTON_SELECT)
#define THREES_BUTTON_ALTTOGGLE  (BUTTON_POWER | BUTTON_UP)

#elif CONFIG_KEYPAD == HM801_PAD
#define THREES_BUTTON_QUIT       BUTTON_POWER
#define THREES_BUTTON_MENU       BUTTON_PLAY
#define THREES_BUTTON_LEFT       BUTTON_LEFT
#define THREES_BUTTON_RIGHT      BUTTON_RIGHT
#define THREES_BUTTON_UP         BUTTON_UP
#define THREES_BUTTON_DOWN       BUTTON_DOWN
#define THREES_BUTTON_TOGGLE     BUTTON_NEXT
#define THREES_BUTTON_TOGGLEBACK BUTTON_PREV
#define THREES_BUTTON_POSSIBLE   (BUTTON_POWER | BUTTON_SELECT)
#define THREES_BUTTON_ALTTOGGLE  BUTTON_SELECT

#else
#error No keymap defined!
#endif

#ifdef HAVE_TOUCHSCREEN
#ifndef THREES_BUTTON_QUIT
#define THREES_BUTTON_QUIT     BUTTON_TOPLEFT
#endif
#ifndef THREES_BUTTON_UP
#define THREES_BUTTON_UP       BUTTON_TOPMIDDLE
#endif
#ifndef THREES_BUTTON_DOWN
#define THREES_BUTTON_DOWN     BUTTON_BOTTOMMIDDLE
#endif
#ifndef THREES_BUTTON_LEFT
#define THREES_BUTTON_LEFT     BUTTON_MIDLEFT
#endif
#ifndef THREES_BUTTON_RIGHT
#define THREES_BUTTON_RIGHT    BUTTON_MIDRIGHT
#endif
#ifndef THREES_BUTTON_TOGGLE
#define THREES_BUTTON_TOGGLE   BUTTON_CENTER
#endif
#ifndef THREES_BUTTON_MENU
#define THREES_BUTTON_MENU     BUTTON_TOPRIGHT
#endif
#ifndef THREES_BUTTON_POSSIBLE
#define THREES_BUTTON_POSSIBLE BUTTON_BOTTOMLEFT
#endif
#endif
